#!/bin/sh

# autostart

# Function to check if an application is already running
is_running() {
    pgrep "$1" > /dev/null 2>&1
}

is_running sxhkd || sxhkd &
is_running ~/.screenlayout/main.sh || ~/.screenlayout/main.sh &
is_running nitrogen || nitrogen --restore &
is_running dwmblocks || dwmblocks &
is_running nm-applet || nm-applet &
is_running volumeicon || volumeicon &
# for laptop users only!
# is_running cbatticon || cbatticon &
is_running conky || conky -c ~/.config/conky/qtile/conky.conf &
is_running udiskie || udiskie &
is_running xclip || xclip &
is_running easyeffects || easyeffects &
is_running solaar || solaar &
~/.config/polybar/launch_polybar.sh

# No more caps lock
setxkbmap -option caps:none


bspc monitor "DP-0" -d 1 2 3 4 5 6 7 8 9
bspc monitor "HDMI-0" -d 1 2 3 4 5 6 7 8 9
# bspc monitor "eDP1" -d 1 2 3 4 5 6 7 8 9

bspc config window_gap 15
bspc config border_width 2
bspc config normal_border_color "#282828"
bspc config focused_border_color "#83a598"

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true
