#!/bin/sh

MULTIMONITOR=1

# autostart

# Function to check if an application is already running
is_running() {
    pgrep "$1" > /dev/null 2>&1
}

is_running sxhkd || sxhkd &
is_running ~/.screenlayout/main.sh || ~/.screenlayout/main.sh &
is_running nitrogen || nitrogen --restore &
is_running dwmblocks || dwmblocks &
is_running nm-applet || nm-applet &
is_running volumeicon || volumeicon &
# for laptop users only!
# is_running cbatticon || cbatticon
is_running conky || conky -c ~/.config/conky/qtile/conky.conf &
is_running udiskie || udiskie &
is_running xclip || xclip &
is_running easyeffects || easyeffects &
is_running solaar || solaar &
is_running picom || picom &
is_running protonvpn || protonvpn &
~/.config/polybar/launch_polybar.sh

# No more caps lock
setxkbmap -option caps:none


for monitor in $(xrandr --query | grep " connected" | cut -d" " -f1); do
do
    # set the workspaces on each monitor to 1-9
    bspc monitor $monitor -d 1 2 3 4 5 6 7 8 9
    #polybar hidden when fullscreen for vlc, youtube, mpv ...
    xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_$monitor)
done
bspc config border_width                  2
bspc config window_gap                    15
bspc config top_padding                   20
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

